### ISSUE TITLE
Showcase Fuse/Camel-K for Integration with external systems

### ISSUE THREAD

**Issue by gbengataylor** [dudash/openshift-microservices#8]
The current design calls for integrating with external APIs and systems via REST, SMTP, SWIFT. We could showcase how Apache Camel/Camel-K can provide this functionality.

**Comment by dudash** [comment]
I like this idea, but I don't want to make the scope of this repo to grow too unwieldy. 
Do you think we could we make Fuse capability in a separate repo that reuses some of the microservices from this repo and adds additional capability?
