### ISSUE TITLE
Add Wildcard router for self-managed APICAST

### ISSUE THREAD

**Issue by gbengataylor** [dudash/openshift-microservices#9]

**Comment by gbengataylor** [comment]
see pull request https://github.com/dudash/openshift-microservices/pull/12

**Comment by gbengataylor** [comment]
TODO: update self-managed apicast to work for any 3scale Manager not just 3scale.net

**Comment by dudash** [comment]
@gbengataylor - is this OBE for 4.x? 
Also, we are adding the assumption that Istio is now required for this demo repo. 3scale is still optional.

**Comment by gbengataylor** [comment]
@dudash i think it's less 4.x and more the newer version of 3scale which now uses the zinc component to for gateway routes

**Comment by dudash** [comment]
Good to close this?

**Comment by gbengataylor** [comment]
yup
